### PR TITLE
Smooth camera movement and solving warnings

### PR DESCRIPTION
**Pull request by luigigamedev**
- Only one main camera reference in GameController;
- Target point created to the camera;
- Smooth movement based on this target point;
- Solving the warnings;

### CODE REVIEW

**Comment by luigigamedev** [comment]
Hi.
I saw your project and enjoyed your idea.
I read the blog, saw the videos.
I realized that I could make some quick changes to make it looks better, at least to test.
I added some smooth movement to the camera.
If you have scene conflict, you can keep yours. I can tell you what configuration I have made.
I believe that I can improve more the camera movement, but this would involve a bigger change.
Maybe I can help with that.
Cheers.

**Comment by tdonlan** [comment]
Hey Luigi, thanks!  I'll test out the changes and merge if they look good -

**Comment by luigigamedev** [comment]
Hey Tim. Have you been busy last weeks? There is a long time since your last modification.
I hope you keep the work.
I am looking to contribute more.
:)

**Comment by tdonlan** [comment]
Hey Luigi -

I've been committing to the dev branch.  Check it out.  Trying to come up
with a stable pre-alpha, then I'll merge back to the master branch.

**Pull request closed without merging**
